#!/bin/bash

RUN_DB=0
RUN_SERVER=0
RUN_CLIENT=0
RUN_TEST=0
PROD=0

mode="up --build"

function print_usage {
    printf "\nUsage: $0 cb/server/client [-m ADDITIONAL_PARAMS]

    -m: Additional params to docker-compose, ex: 'build/down -v/...'

"
}


while (( "$#" )); do
    case "$1" in

        # Module
        db)
            RUN_DB=1
            shift
        ;;

        server)
            RUN_SERVER=1
            shift
        ;;

        client)
            RUN_CLIENT=1
            shift
        ;;

        test)
            RUN_TEST=1
            shift
        ;;

        -m)
            mode=$2
            shift 2
        ;;

        --prod)
            PROD=1
            shift 1
        ;;
        
        -h)
            print_usage
            exit 0
        ;;

        # Option
        *)
            echo "Unsupported param '$1'"
            exit 1
        ;;

    esac
done

cmd="docker-compose --project-directory ."
profile="dev"

if [[ "$PROD" -eq 1 ]]; then
   profile="prod" 
fi

if [[ "$RUN_DB" -eq 1 || "$RUN_TEST" -eq 1 ]]; then
    cmd="$cmd -f deployment/db/docker-compose.$profile.yml"
fi

if [[ "$RUN_CLIENT" -eq 1 ]]; then
    cmd="$cmd -f deployment/client/docker-compose.$profile.yml"
fi

if [[ "$RUN_SERVER" -eq 1 || "$RUN_TEST" -eq 1 ]]; then
    cmd="$cmd -f deployment/server/docker-compose.$profile.yml"
fi

if [[ "$RUN_TEST" -eq 1 ]]; then
    cmd="$cmd -f deployment/test/docker-compose.$profile.yml"
fi

echo $cmd

bash -c "$cmd $mode"