version: "3.1"

services:
  db:
    container_name: api_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db-cannal


  adminer:
    container_name: api_admin
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 4001:8080

networks:
  db-cannal:
    driver: bridge