version: "3.1"

services:
  db:
    container_name: api_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    container_name: api_admin
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 4001:8080